apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
nameSuffix: -blue
images:
- name: cicd-gke
  newName: serhii714/cicd-gke
  newTag: a61c52ec5dd8cdb6abfbac4806e491ee88e51976
labels:
  - pairs:
      app: cicd-gke-blue
    includeSelectors: true
