apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
nameSuffix: -blue
images:
- name: cicd-gke
  newName: serhii714/cicd-gke
  newTag: f8f2f42f40f8f97aeaee62862530a51627d53b11
labels:
  - pairs:
      app: cicd-gke-blue
    includeSelectors: true
