apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
nameSuffix: -blue
images:
- name: cicd-gke
  newName: serhii714/cicd-gke
  newTag: 43aa1bcf88b510e80523193446755a823a918603
labels:
  - pairs:
      app: cicd-gke-blue
    includeSelectors: true
