apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
nameSuffix: -green
images:
- name: cicd-gke
  newName: serhii714/cicd-gke
  newTag: d1fd873da25490a7c4b357f0dacbf2285e38dcd1
labels:
  - pairs:
      app: cicd-gke-green
    includeSelectors: true
