apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
nameSuffix: -green
images:
- name: cicd-gke
  newName: serhii714/cicd-gke
  newTag: latest
labels:
  - pairs:
      app: cicd-gke-green
    includeSelectors: true
