apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: cicd-gke
  newName: serhii714/cicd-gke
  newTag: 99dd79c85ca82f04a33fbf36a80f446cfcb4b8ee
