apiVersion: v1
kind: Service
metadata:
  name: cicd-gke-loadbalancer
  namespace: cicd-gke
spec:
  type: LoadBalancer
  selector:
    app: cicd-gke
  ports:
  - protocol: TCP
    port: 80
    targetPort: flask
